# Generated by Django 5.2.2 on 2026-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rea_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('customer', 'Покупатель'), ('vendor', 'Продавец')], default='customer', verbose_name='Роль'),
        ),
    ]
