# Generated by Django 5.2.2 on 2026-03-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rea_users', '0005_alter_contact_created_at_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контакты пользователя'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
