# Generated by Django 5.2.2 on 2026-02-28 23:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Первичный ключ')),
                ('label', models.CharField(max_length=50, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Принимает заказы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Магазин',
                'ordering': ['-created_at'],
            },
        ),
    ]
