# Generated by Django 5.2.2 on 2026-03-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rea_orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
