# Generated by Django 5.2.2 on 2026-03-02 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rea_catalog', '0001_initial'),
        ('rea_orders', '0002_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Первичный ключ')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='rea_orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='rea_catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказанная позиция',
                'constraints': [models.UniqueConstraint(fields=('order_id', 'product'), name='unique_order_item')],
            },
        ),
    ]
