# Generated by Django 5.2.2 on 2026-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rea_orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказанная позиция'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2026-03-01T00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
