# Generated by Django 5.2.2 on 2026-03-01 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rea_vendors', '0002_alter_shop_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Первичный ключ')),
                ('label', models.CharField(max_length=40, verbose_name='Название')),
                ('shops', models.ManyToManyField(blank=True, related_name='categories', to='rea_vendors.shop', verbose_name='Магазины')),
            ],
            options={
                'verbose_name': 'Категория',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Первичный ключ')),
                ('label', models.CharField(max_length=80, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Модель')),
                ('ext_id', models.CharField(verbose_name='Внешний ИД')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('price_rrc', models.PositiveIntegerField(verbose_name='Рекомендуемая розничная цена')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rea_catalog.category', verbose_name='Категория')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_infos', to='rea_vendors.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'ordering': ['-created_at'],
            },
        ),
    ]
